[helm values] Add note on evict-local-storage-pods
Setting it to true causes:

```
Error: unknown command "true" for "descheduler"
Run 'descheduler --help' for usage.
unknown command "true" for "descheduler"
```

This is confusing as other references to this parameter (outside of helm) do ask you to set it to true.

Would be better to just accept the value here, but for now this is what I can help with.